layout_spectrum: 0.9715018160641193
typography_spectrum: 0.20882160682231188
color:
  saturation: 0.5700326797086746
  brandStrength: 0.05576370866037905
  rhythmicContrast: 0.6286129332147539
  brandColors:
    - '#00AEEF'
    - '#000000'
    - '#A3A8AE'
    - '#697078'
    - '#FFFFFF'
  lightness: 0.4414194088894874
title: Blueriver Quant Labs
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: a coalition of experimental thinkers
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: UA-77227516-1
  facebook: null
name: Blueriver Quant Labs
favicon: null
navigation:
  - name: Real Estate Q-Lab
    id: e4dbd5a2-ca1f-4940-afae-4b80dd1a0188
    type: content
opengraph:
  image: null
  type: null
  appId: null
