name: Blueriver Quant Labs
favicon: null
layout_spectrum: 0.7061070040799677
typography_spectrum: 0.23629635712131858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3650056931655854
  lightness: 0.11404543532989919
  saturation: 0.3171618366613984
  rhythmicContrast: 0.3167526158504188
purpose: []
